version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "calfire-gis-mcp-server"
s3_bucket = "calfire-gis-mcp-server-deploy-3fa9d2"
s3_prefix = "calfire-gis-mcp-server"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BudgetEmail=XXXXXX"
confirm_changeset = false
fail_on_empty_changeset = false